### ISSUE TITLE
Workaround for KAFKA-4408

### ISSUE THREAD

**Issue by chris-zen** [jpzk/mockedstreams#15]
Hi, there is a bug in `ProcessorTopologyTestDriver` for 0.10.1.0 that produces an error when working with KTables:

```
Exception in thread "main" org.apache.kafka.streams.errors.StreamsException: task [0_0] Could not find partition info for topic: topic-name
```

See [KAFKA-4408](https://issues.apache.org/jira/browse/KAFKA-4408) for more information.

I was wondering if there is any workaround that could be implemented in `MockedStreams`.

**Comment by jpzk** [comment]
Looks like this is resolved by https://github.com/apache/kafka/pull/2629 in the latest. Can I close this ticket? :)

**Comment by chris-zen** [comment]
:+1:
