### ISSUE TITLE
How to test processors / transformers that implement punctuate

### ISSUE THREAD

**Issue by eli-jordan** [jpzk/mockedstreams#18]
I have an implementation of transformer, that makes use of the punctuate method. However, I haven't been able to figure out how to have this called using mocked streams. I even tried using a custom time extractor, with no luck.

Is it possible to force punctuate to be called when using mocked streams? Or should I just test this portion of the application with real brokers?

**Comment by efeller** [comment]
@eli-jordan I am wondering the same. Did you manage to find a solution besides using real brokers?

**Comment by jpzk** [comment]
"TopologyTestDriver supports punctuations, too. Event-time punctuations are triggered automatically based on the processed records' timestamps. Wall-clock-time punctuations can also be triggered by advancing the test driver's wall-clock time. The driver's wall-clock time must be advanced manually (this is for test stability). " https://docs.confluent.io/current/streams/developer-guide/test-streams.html
