### ISSUE TITLE
MockedStream could allow to specify the order in which events are submitted to the topology

### ISSUE THREAD

**Issue by sv3nd** [jpzk/mockedstreams#19]
Thanks for designing MockedStreams! I started to use it yesterday and I find it super handy to validate Kafka Streams topologies locally. 

One feature that I think could be added is the ability to fine control the order in which the events are submitted to the tested topology. 

For example, in case we test a topology with a KStream joined with a KTable, the joins operation is triggered when the stream receive an event and not when the KTable does, which implies that sending events in various order may influence the end result and therefore the outcome that the test should validate. 

Additionally, it would be cool to be able to design longer event scenarios, like "send some messages to topicA, then some to topic B, then some more to topic A", like so: 

```
    val firstInputForTopicA = Seq(("x", int(1)), ("y", int(2)))
    val firstInputForTopicB = Seq(("x", int(4)), ("y", int(3)), ("y", int(5)))
    val secondInputForTopicA = Seq(("y", int(4)))

    val expectedOutput = Seq(("x", 5), ("y", 5), ("y", 7), ("y", 9))

    val builder = MockedStreams()
      .topology(topologyTables)
      .input(InputATopic, strings, ints, firstInputForTopicA)
      .input(InputBTopic, strings, ints, firstInputForTopicB)
      .input(InputATopic, strings, ints, secondInputForTopicA)
```

At the moment, as I understand it `MockedStream` submits the events of each topic all at once:

```
private def produce(driver: Driver) = {
      inputs.foreach { case (topic, input) =>
        input.seq.foreach { case (key, value) =>
          driver.process(topic, key, value)
        }
      }
    }
```
Also, since `inputs` is a map, I think scala does not guarantee the order in which its keys are traversed during the `foreach`. 

I have started experimenting with the code and now have a forked version with the desired behaviour above. The change is pretty small actually. I'll submit the corresponding PR shortly. It would be great to get your opinion about this and hopefully get it merged :) 

Cheers

**Comment by jpzk** [comment]
Added comments in the PR, overall great contribution, let's put it into the 1.4.0 release.
