### ISSUE TITLE
FileNotFoundException pointing to fixed path when library is used

### ISSUE THREAD

**Issue by TimoMeijer** [jpzk/mockedstreams#3]
java.io.FileNotFoundException: \Users\jpzk\s\d\mockedstreams\target\scala-2.11\scoverage-data\scoverage.measurements.1

**Comment by jpzk** [comment]
Thanks for noticing, I had the same problem when I tested it against a project. It was the scoverage plugin, I removed it entirely from mockedstreams in the morning. Should work now.
