### ISSUE TITLE
Add record to state store before test

### ISSUE THREAD

**Issue by efeller** [jpzk/mockedstreams#30]
Hi all,

I wonder if it is possible somehow to add a record to a state store before starting the test? I looked over the API and could not find a way.  stateTable() seems to return a map. However, I could not find a way to use that in conjunction with starting topology. Any idea?

Thanks,
Eugen

**Comment by Pitometsu** [comment]
looks like you can use other stream for that as an input like that:

```
      consumerBuilder
        .input(topics.name.state, nameIdSerde, nameStateSerde,
          supplierBuilder.output(topics.name.state, nameIdSerde, nameStateSerde, 1))
```
Don't forget to add `supplierBuilder.stores(Seq(topics.name.state))`.

**Comment by efeller** [comment]
Great. Thanks a lot @Pitometsu. Will give it a try. :-)

**Comment by jpzk** [comment]
Can we close this issue? :)
