### ISSUE TITLE
Support Kafka 2.0

### ISSUE THREAD

**Issue by nvladimiroff** [jpzk/mockedstreams#34]
Kafka 2.0 has been released and it'd be useful if mockedstreams supported it.

**Comment by mowczare** [comment]
Also, 1.8.0 version supporting Kafka 1.1.1 has not been pushed to mvn repo.

**Comment by jpzk** [comment]
@nvladimiroff 2.0.0 changed the API a lot, the ProcessorTopologyTestDriver is not existent anymore. I just had a look the closest might be https://github.com/apache/kafka/blob/trunk/streams/test-utils/src/main/java/org/apache/kafka/streams/TopologyTestDriver.java, I'll have a look later
@mowczare My apologies I'll check soon!

**Comment by jpzk** [comment]
@nvladimiroff v2.0 is released
@mowczare Thanks for letting me know, it is now in Maven Central
