### ISSUE TITLE
Should be able to set message timestamp when producing a Record.

### ISSUE THREAD

**Issue by danhamiltonsky** [jpzk/mockedstreams#37]
So that I can test Join Windows in a Kafka Streams Topology
I want to be able to set message timestamp when producing a Record.

Presently `MockedStreams.produce` calls Kafka's `ProcessorTopologyTestDriver.process` which sets a default timestamp of 0. This prevents testing Join windows of Kafka streams as cannot produce records with different timestamps.

**Comment by jpzk** [comment]
Merged and released in Mocked Streams 2.1

**Comment by jpzk** [comment]
Thanks again for the contribution! 👍
