### ISSUE TITLE
NoSuchMethodError Exception [might be related to the fact i am using kafka streams 2.0.1]

### ISSUE THREAD

**Issue by nitayk** [jpzk/mockedstreams#40]
Hey,
We are currently using Kafka streams 1.1.1.
When trying to move to version 2.0.1 (skipped 2.0.0 as it had a bug in scala).
When running my tests, and get to the point i am doing:
`streamsMock.stateTable(SOME_STORE_NAME) shouldEqual SOME_VALUE`
I get the following error:
> An exception or error caused a run to abort: org.apache.kafka.streams.processor.internals.StreamTask.<init>(Lorg/apache/kafka/streams/processor/TaskId;Ljava/util/Collection;Lorg/apache/kafka/streams/processor/internals/ProcessorTopology;Lorg/apache/kafka/clients/consumer/Consumer;Lorg/apache/kafka/streams/processor/internals/ChangelogReader;Lorg/apache/kafka/streams/StreamsConfig;Lorg/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl;Lorg/apache/kafka/streams/processor/internals/StateDirectory;Lorg/apache/kafka/streams/state/internals/ThreadCache;Lorg/apache/kafka/common/utils/Time;Lorg/apache/kafka/clients/producer/Producer;)V 
> java.lang.NoSuchMethodError: org.apache.kafka.streams.processor.internals.StreamTask.<init>(Lorg/apache/kafka/streams/processor/TaskId;Ljava/util/Collection;Lorg/apache/kafka/streams/processor/internals/ProcessorTopology;Lorg/apache/kafka/clients/consumer/Consumer;Lorg/apache/kafka/streams/processor/internals/ChangelogReader;Lorg/apache/kafka/streams/StreamsConfig;Lorg/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl;Lorg/apache/kafka/streams/processor/internals/StateDirectory;Lorg/apache/kafka/streams/state/internals/ThreadCache;Lorg/apache/kafka/common/utils/Time;Lorg/apache/kafka/clients/producer/Producer;)V
> 	at org.apache.kafka.streams.TopologyTestDriver.<init>(TopologyTestDriver.java:332)
> 	at org.apache.kafka.streams.TopologyTestDriver.<init>(TopologyTestDriver.java:225)
> 	at org.apache.kafka.streams.TopologyTestDriver.<init>(TopologyTestDriver.java:211)
> 	at com.madewithtea.mockedstreams.MockedStreams$Builder.stream(MockedStreams.scala:116)
> 	at com.madewithtea.mockedstreams.MockedStreams$Builder.withProcessedDriver(MockedStreams.scala:125)
> 	at com.madewithtea.mockedstreams.MockedStreams$Builder.stateTable(MockedStreams.scala:75)

I think this relates to the version not being compatible, but I might be something else.

I will try to find some time and maybe check it myself.

If you need me to provide more info - please let me know.

Thanks anyway,

**Comment by nitayk** [comment]
Opened a PR: https://github.com/jpzk/mockedstreams/pull/41

**Comment by jpzk** [comment]
Seems like we can close this issue.
