### ISSUE TITLE
Support Kafka 2.1.0

### ISSUE THREAD

**Issue by mowczare** [jpzk/mockedstreams#43]
Kafka 2.1.0 has been available since quite some time, it would be nice to have `mockedstreams` officially updated to support 2.1.0 version.

**Comment by chadjosephson-octanner** [comment]
I would love to see this PR merged. There are a few fixes in the 2.1 version of Kafka Streams that I need. Currently `mockedstreams` is the only dependency keeping me from migrating.

**Comment by mowczare** [comment]
Closing since it's already merged. Thanks!
