### ISSUE TITLE
2.13 support

### ISSUE THREAD

**Issue by tOverney** [jpzk/mockedstreams#59]
Kafka itself now supports 2.13,
Can this be cross compiled with 2.13?

**Comment by jpzk** [comment]
Mocked streams depends on this https://mvnrepository.com/artifact/org.apache.kafka/kafka-streams-scala, and it has not been published for 2.13.

**Comment by jpzk** [comment]
Scala 2.13 for Kafka is scheduled for 2.4.0 Kafka release. https://t.co/TfuX11ZK4M?amp=1
