### ISSUE TITLE
Dependence on BETA version of slf4j-api

### ISSUE THREAD

**Issue by andretobu** [jpzk/mockedstreams#64]
By using the MdocPlugin
which brings in a libraryDependency on org.scalameta:mdoc
which currenctly depends on slf4j-api 1.8.0-**beta**4
this project depends on slf4j-api 1.8.0-**beta**4
and forces clients to provide a corresponding implementation.

Is this desired?

see https://github.com/scalameta/mdoc/issues/298

**Comment by jpzk** [comment]
Good catch, let's see what the mdoc maintainers will do about it

**Comment by ivanoronee** [comment]
@jpzk The mdoc changes seem to have been merged. Perhaps it is now time to upgrade the mdoc version being used here
https://github.com/scalameta/mdoc/commit/04b3806a758580f2acefc0159111cc916fc646ec

**Comment by ivanoronee** [comment]
> @jpzk The mdoc changes seem to have been merged. Perhaps it is now time to upgrade the mdoc version being used here
> [scalameta/mdoc@04b3806](https://github.com/scalameta/mdoc/commit/04b3806a758580f2acefc0159111cc916fc646ec)

I made this change https://github.com/jpzk/mockedstreams/pull/66. Could you please review and merge in if all is ok
