### ISSUE TITLE
Calling output more than once causes the topology to be executed multiple times

### ISSUE THREAD

**Issue by eliaslevy** [jpzk/mockedstreams#7]
The driver should be memorized instead of being recreated and reexecuted on each call to output.

**Comment by jpzk** [comment]
This is intended, so we don't have to keep state (which would unnecessary overcomplicate the code). Given the assumption you use Mocked Streams for unit-testing, you might not have so much data to process, consequently, multiple runs will not take long. I hope I could clarify this design.
